In [9]:
import pandas as pd

df = pd.read_parquet("../data/processed/messages_classified")
df

,id,group_name,text,datetime,political_category,year,month
0,89617,channel_1683101758,It's still incomprehensible how some really go...,2023-11-09 10:27:34,Outliers,2023,11
1,82216,channel_1683101758,Take your mongoloid akhbarring elsewhere you p...,2023-11-03 09:53:00,Outliers,2023,11
2,84147,channel_1683101758,regime change is always the best,2023-11-04 14:38:39,Politic,2023,11
3,88205,channel_1683101758,"If it was a genocide, then I will say it was a...",2023-11-07 19:47:33,Politic,2023,11
4,99397,channel_1683101758,Finally he found the time to admit it,2023-11-30 14:11:58,Outliers,2023,11
...,...,...,...,...,...,...,...
48425263,1915,channel_1925564028,STORY PROTOCOL ( Fund Raised $134M ) launched...,2025-01-03 11:13:32,Non Politic,2025,1
48425264,540,channel_2083547614,🚀 ATTENTION GATE Aspirants!\n\nGeeksforGeeks i...,2025-01-11 10:14:33,Outliers,2025,1
48425265,196,channel_2139463293,𝗠𝗶𝗰𝗿𝗼𝘀𝗼𝗳𝘁 𝗙𝗥𝗘𝗘 𝗣𝗼𝘄𝗲𝗿𝗕𝗜 𝗖𝗲𝗿𝘁𝗶𝗳𝗶𝗰𝗮𝘁𝗶𝗼𝗻 𝗖𝗼𝘂𝗿𝘀𝗲 😍 ...,2025-01-10 05:23:57,Non Politic,2025,1
48425266,201,channel_2066102094,1. Start Investing With A Game Plan\n\nBefore ...,2025-01-11 13:56:52,Non Politic,2025,1
48425267,197,channel_2084577860,𝐒𝐐𝐋 𝐅𝐑𝐄𝐄 𝐂𝐞𝐫𝐭𝐢𝐟𝐢𝐜𝐚𝐭𝐢𝐨𝐧 𝐂𝐨𝐮𝐫𝐬𝐞𝐬 😍\n\n🚀 Here are...,2025-01-11 05:18:23,Politic,2025,1

In [11]:
resultado = df.groupby('political_category').size().reset_index(name='contagem')
print(resultado)

  political_category  contagem
0        Non Politic  18103806
1           Outliers  15533014
2            Politic  14788448

In [14]:
df_full = pd.read_parquet("../data/processed/messages_preprocessed")
df_full

,id,group_name,text,timestamp,file_path,text_clean,datetime,language,date_type,clean_text,year,month
0,79832,channel_1683101758,@admin This account is threatening members,1698894032,file:///home/students/moliveira/telegram_2024/...,This account is threatening members,2023-11-02 03:00:32,en,2023-11-02 03:00:32,account threaten member,2023,11
1,95211,channel_1683101758,Most of the Gay porn search on google is made ...,1700613774,file:///home/students/moliveira/telegram_2024/...,Most of the Gay porn search on google is made ...,2023-11-22 00:42:54,en,2023-11-22 00:42:54,gay porn search google make pakistan happens s...,2023,11
2,205651,channel_1463755585,"Symbolism is everything , pig shagger Cameron ...",1699975266,file:///home/students/moliveira/telegram_2024/...,"Symbolism is everything , pig shagger Cameron ...",2023-11-14 15:21:06,en,2023-11-14 15:21:06,symbolism everything pig shagger cameron back ...,2023,11
3,208047,channel_1463755585,"""An emergent pandemic hit the world end of 201...",1701007810,file:///home/students/moliveira/telegram_2024/...,"""An emergent pandemic hit the world end of 201...",2023-11-26 14:10:10,en,2023-11-26 14:10:10,emergent pandemic hit world end destroy live c...,2023,11
4,87388,channel_1683101758,"I'm just saying what I would do, live and let ...",1699360132,file:///home/students/moliveira/telegram_2024/...,"I'm just saying what I would do, live and let ...",2023-11-07 12:28:52,en,2023-11-07 12:28:52,say would live let live long one harm anyone e...,2023,11
...,...,...,...,...,...,...,...,...,...,...,...,...
48425263,724,channel_2000341787,🦆 $DUCK Listing on OKX + AirDrop Announced! \...,1736441824,file:///home/students/moliveira/telegram_2024/...,🦆 $DUCK Listing on OKX + AirDrop Announced! \...,2025-01-09 16:57:04,en,2025-01-09 16:57:04,duck list okx airdrop announce ▪️okx listing d...,2025,1
48425264,809,channel_1648837346,2025/1/3 📈 \n\nToday's Newsletter & Twitter (P...,1735937527,file:///home/students/moliveira/telegram_2024/...,2025/1/3 📈 \n\nToday's Newsletter & Twitter (P...,2025-01-03 20:52:07,en,2025-01-03 20:52:07,today newsletter twitter please follow like th...,2025,1
48425265,618,channel_1930983957,"The world stands on a precipice, and the trend...",1736817377,file:///home/students/moliveira/telegram_2024/...,"The world stands on a precipice, and the trend...",2025-01-14 01:16:17,en,2025-01-14 01:16:17,world stand precipice trend good united state ...,2025,1
48425266,222,channel_2080462919,🧠 How to Use ChatGPT for SEO ?\n\nChatGPT is ...,1736419632,file:///home/students/moliveira/telegram_2024/...,🧠 How to Use ChatGPT for SEO ?\n\nChatGPT is ...,2025-01-09 10:47:12,en,2025-01-09 10:47:12,use chatgpt seo chatgpt powerful tool streamli...,2025,1
48425267,527,channel_2098876171,"The $5 to $10,000 Challenge Starts Now! \n\n-...",1736164400,file:///home/students/moliveira/telegram_2024/...,"The $5 to $10,000 Challenge Starts Now! \n\n-...",2025-01-06 11:53:20,en,2025-01-06 11:53:20,challenge start previous challenge smash goal ...,2025,1

In [16]:
pk_cols = ["id", "group_name"]

# ────────────────────────────────────────────────────────────────
# 1. VALIDAÇÃO DE CHAVE PRIMÁRIA (PK)
# ────────────────────────────────────────────────────────────────
def validate_pk(df, name):
    print(f"\nValidando PK para: {name}")
    print(f"Total de linhas: {len(df)}")
    
    # Verifica nulos nas colunas de chave
    nulls = df[pk_cols].isnull().sum().sum()
    print(f"Valores nulos nas colunas de chave: {nulls}")
    
    # Verifica duplicatas da combinacao id + group_name
    dupes = df.duplicated(subset=pk_cols).sum()
    print(f"Chaves duplicadas (id + group_name): {dupes}")
    
    is_valid = (nulls == 0) and (dupes == 0)
    if is_valid:
        print(f"-> OK: '{name}' forma uma Chave Primária válida e única!")
    else:
        print(f"-> AVISO: '{name}' POSSUI DUPLICATAS OU NULOS NAS CHAVES!")
    return is_valid

valid_full = validate_pk(df_full, "df_full")
valid_classified = validate_pk(df, "df")

Validando PK para: df_full
Total de linhas: 48425268
Valores nulos nas colunas de chave: 0
Chaves duplicadas (id + group_name): 0
-> OK: 'df_full' forma uma Chave Primária válida e única!

Validando PK para: df
Total de linhas: 48425268
Valores nulos nas colunas de chave: 0
Chaves duplicadas (id + group_name): 0
-> OK: 'df' forma uma Chave Primária válida e única!

In [18]:
print("Cruzando os datasets para validar o alinhamento...")
df_check = pd.merge(
    df,
    df_full,
    on=pk_cols,
    suffixes=('_class', '_full'),
    how='inner'
)

print(f"Total de registros cruzados: {len(df_check)}")

# 2. Verificar se a coluna 'text' bate 100%
if 'text_class' in df_check.columns and 'text_full' in df_check.columns:
    match_text = (df_check['text_class'] == df_check['text_full']).all()
    print(f"-> A coluna 'text' é idêntica em todas as linhas? {match_text}")
    if not match_text:
        diffs = (df_check['text_class'] != df_check['text_full']).sum()
        print(f"   Atenção: Existem {diffs} divergências no 'text'.")

# 3. Verificar se a coluna 'clean_text' bate 100% (caso o df_classified já possua essa coluna)
if 'clean_text_class' in df_check.columns and 'clean_text_full' in df_check.columns:
    match_clean = (df_check['clean_text_class'] == df_check['clean_text_full']).all()
    print(f"-> A coluna 'clean_text' é idêntica em todas as linhas? {match_clean}")
    if not match_clean:
        diffs_clean = (df_check['clean_text_class'] != df_check['clean_text_full']).sum()
        print(f"   Atenção: Existem {diffs_clean} divergências no 'clean_text'.")
else:
    print("-> A coluna 'clean_text' não estava presente em df_classified (será importada agora do df_full).")

Cruzando os datasets para validar o alinhamento...
Total de registros cruzados: 48425268
-> A coluna 'text' é idêntica em todas as linhas? True
-> A coluna 'clean_text' não estava presente em df_classified (será importada agora do df_full).

In [20]:
df_final = pd.merge(
    df,
    df_full[pk_cols + ["clean_text"]],
    on=pk_cols,
    how="inner"
)

In [21]:
df_final

,id,group_name,text,datetime,political_category,year,month,clean_text
0,89617,channel_1683101758,It's still incomprehensible how some really go...,2023-11-09 10:27:34,Outliers,2023,11,still incomprehensible really good university ...
1,82216,channel_1683101758,Take your mongoloid akhbarring elsewhere you p...,2023-11-03 09:53:00,Outliers,2023,11,take mongoloid akhbarring elsewhere pedophile ...
2,84147,channel_1683101758,regime change is always the best,2023-11-04 14:38:39,Politic,2023,11,regime change always best
3,88205,channel_1683101758,"If it was a genocide, then I will say it was a...",2023-11-07 19:47:33,Politic,2023,11,genocide say genocide
4,99397,channel_1683101758,Finally he found the time to admit it,2023-11-30 14:11:58,Outliers,2023,11,finally find time admit
...,...,...,...,...,...,...,...,...
48425263,1915,channel_1925564028,STORY PROTOCOL ( Fund Raised $134M ) launched...,2025-01-03 11:13:32,Non Politic,2025,1,story protocol fund raise launch agent network...
48425264,540,channel_2083547614,🚀 ATTENTION GATE Aspirants!\n\nGeeksforGeeks i...,2025-01-11 10:14:33,Outliers,2025,1,attention gate aspirant geeksforgeeks launch s...
48425265,196,channel_2139463293,𝗠𝗶𝗰𝗿𝗼𝘀𝗼𝗳𝘁 𝗙𝗥𝗘𝗘 𝗣𝗼𝘄𝗲𝗿𝗕𝗜 𝗖𝗲𝗿𝘁𝗶𝗳𝗶𝗰𝗮𝘁𝗶𝗼𝗻 𝗖𝗼𝘂𝗿𝘀𝗲 😍 ...,2025-01-10 05:23:57,Non Politic,2025,1,𝗠𝗶𝗰𝗿𝗼𝘀𝗼𝗳𝘁 𝗙𝗥𝗘𝗘 𝗣𝗼𝘄𝗲𝗿𝗕𝗜 𝗖𝗲𝗿𝘁𝗶𝗳𝗶𝗰𝗮𝘁𝗶𝗼𝗻 𝗖𝗼𝘂𝗿𝘀𝗲 ki...
48425266,201,channel_2066102094,1. Start Investing With A Game Plan\n\nBefore ...,2025-01-11 13:56:52,Non Politic,2025,1,start invest game plan invest first dollar sto...
48425267,197,channel_2084577860,𝐒𝐐𝐋 𝐅𝐑𝐄𝐄 𝐂𝐞𝐫𝐭𝐢𝐟𝐢𝐜𝐚𝐭𝐢𝐨𝐧 𝐂𝐨𝐮𝐫𝐬𝐞𝐬 😍\n\n🚀 Here are...,2025-01-11 05:18:23,Politic,2025,1,𝐒𝐐𝐋 𝐅𝐑𝐄𝐄 𝐂𝐞𝐫𝐭𝐢𝐟𝐢𝐜𝐚𝐭𝐢𝐨𝐧 𝐂𝐨𝐮𝐫𝐬𝐞𝐬 top resource of...

In [22]:
path_classified = Path("../data/processed/messages_classified2")

df_final.to_parquet(
    path_classified,
    engine="pyarrow",
    partition_cols=["year", "month"],
    index=False
)

print("Sucesso! A base 'messages_classified' foi validada e reescrita contendo a coluna 'clean_text' perfeitamente alinhada.")

Sucesso! A base 'messages_classified' foi validada e reescrita contendo a coluna 'clean_text' perfeitamente alinhada.

In [3]:
if "predicted_class" in df.columns:
    df = df.rename(columns={"predicted_class": "political_category"})
    print("Coluna 'predicted_class' renomeada para 'political_category' com sucesso!")
else:
    print("Aviso: A coluna 'predicted_class' não foi encontrada. Verifique os nomes.")

Coluna 'predicted_class' renomeada para 'political_category' com sucesso!

In [4]:
df

,id,group_name,text,datetime,political_category,year,month
0,89617,channel_1683101758,It's still incomprehensible how some really go...,2023-11-09 10:27:34,Outliers,2023,11
1,82216,channel_1683101758,Take your mongoloid akhbarring elsewhere you p...,2023-11-03 09:53:00,Outliers,2023,11
2,84147,channel_1683101758,regime change is always the best,2023-11-04 14:38:39,Politic,2023,11
3,88205,channel_1683101758,"If it was a genocide, then I will say it was a...",2023-11-07 19:47:33,Politic,2023,11
4,99397,channel_1683101758,Finally he found the time to admit it,2023-11-30 14:11:58,Outliers,2023,11
...,...,...,...,...,...,...,...
48425263,1915,channel_1925564028,STORY PROTOCOL ( Fund Raised $134M ) launched...,2025-01-03 11:13:32,Non Politic,2025,1
48425264,540,channel_2083547614,🚀 ATTENTION GATE Aspirants!\n\nGeeksforGeeks i...,2025-01-11 10:14:33,Outliers,2025,1
48425265,196,channel_2139463293,𝗠𝗶𝗰𝗿𝗼𝘀𝗼𝗳𝘁 𝗙𝗥𝗘𝗘 𝗣𝗼𝘄𝗲𝗿𝗕𝗜 𝗖𝗲𝗿𝘁𝗶𝗳𝗶𝗰𝗮𝘁𝗶𝗼𝗻 𝗖𝗼𝘂𝗿𝘀𝗲 😍 ...,2025-01-10 05:23:57,Non Politic,2025,1
48425266,201,channel_2066102094,1. Start Investing With A Game Plan\n\nBefore ...,2025-01-11 13:56:52,Non Politic,2025,1
48425267,197,channel_2084577860,𝐒𝐐𝐋 𝐅𝐑𝐄𝐄 𝐂𝐞𝐫𝐭𝐢𝐟𝐢𝐜𝐚𝐭𝐢𝐨𝐧 𝐂𝐨𝐮𝐫𝐬𝐞𝐬 😍\n\n🚀 Here are...,2025-01-11 05:18:23,Politic,2025,1